### ISSUE TITLE
Why need setting the display name of the cluster for that I already have a cluster name in azure portal? What for?

### ISSUE THREAD

**Issue by Sam--Shan** [Microsoft/HDInsightVSCodeExtension#10]
what does the display name used for? what's the difference between these two conditions: set the display name and not set?
![image](https://user-images.githubusercontent.com/10590637/75544635-5c96c880-5a5f-11ea-801b-9a3b2fcf4414.png)

**Comment by zesluo** [comment]
not make much difference actually. it will not affect the function of cluster. You can just take it as giving a nick name
