### ISSUE TITLE
Failed to connect to Jupyter notebook. http://localhost:8888/ TypeError: Only absolute URLs are supported

### ISSUE THREAD

**Issue by virtualdvid** [Microsoft/HDInsightVSCodeExtension#12]
I'm following this [documentation ](https://docs.microsoft.com/en-us/azure/hdinsight/hdinsight-for-vscode). All of it is going good util I highlight the code and click `Spark: PySpark Interactive`. Then I got:

`Failed to connect to Jupyter notebook. http://localhost:8888/ TypeError: Only absolute URLs are supported`

Jupyter notebbok launches fine if I run it in the terminal in the env `hdinsightJupyter`

**Comment by zesluo** [comment]
Hello Virtualdvid, Thanks for your feedback! By the way, please check the section 'Known issues' on the bottom of this document. I think that you may need to use the 2020.4.76186 version of ms-python to avoid this issue

**Comment by virtualdvid** [comment]
@zesluo Thanks for your fast answer. My bad I didn't read the entire document. I got a `server returned 404` error when I tried to get another python version. I have to get it through [`vsix`](https://www.vsixhub.com/vsix/28274/).

Thanks!
