### ISSUE TITLE
BUG 295843:[HDIVSCode]Output panel keep showing after finish analyzing a query, from customer

### ISSUE THREAD

**Issue by zesluo** [Microsoft/HDInsightVSCodeExtension#2]
Repo steps:
Hello,
I'm using the latest version of the extension and I was wondering if it is possible to stop it from making visible the output panel everytime a query is modified.

I hide the output panel, modify a query and after it has finished analyzing it (I suppose) it shows the output panel again.

**Comment by zesluo** [comment]
A PR for it has been checked in.

**Comment by jingyanjingyan** [comment]
Verify as fix with HDInsight 1.1.3
