### ISSUE TITLE
Error 'vscode.previewHtml' not found

### ISSUE THREAD

**Issue by ArtichA** [Microsoft/HDInsightVSCodeExtension#4]
It looks like VSCode v1.3.3 has already removed 'vscode.previewHtml' API. Executing a hive query always returns the error  'vscode.previewHtml' not found.

**Comment by mandywAtGitHub** [comment]
Thanks for reporting this to us. We've a fix for this issue. Will release it soon.

**Comment by mebibou** [comment]
how soon is soon? this is a real blocker here

**Comment by jingyanjingyan** [comment]
Fix with HDInsight 1.1.3
