### ISSUE TITLE
Error: command 'hdinsgiht.jupyter.execRangeInKernel' already exists

### ISSUE THREAD

**Issue by widovanheemstra** [Microsoft/HDInsightVSCodeExtension#7]
I have setup the extension as described online. When I try to run some code in the Interactive Window, I get the following error:

[2019-9-25:15:1:18] [Error] PySpark Interactive Error: Error: command 'hdinsgiht.jupyter.execRangeInKernel' already exists

The Livy cluster is running as I can see from the List Cluster command:

[2019-9-25:15:7:29] [Info] List Azure BD cluster:
=========================================================
Subscription/Type                       	ClusterName                   	ClusterType              Status    
Generic Livy                            	JupyterHub: http://127.0.0.1:8	Spark(Version: unknown)  Running   
                                        	888 (NONE)                    	                                   
=========================================================
[2019-9-25:15:7:29] [Info] list cluster(s) successfully!

So apart from the typo 'hdinsgiht.' how and where can I fix this issue? My code doesn't get executed now.

I'm using the 1.1.6 version of this plugin.

**Comment by c0pLus13** [comment]
me too , have erro log:

**Comment by Sam--Shan** [comment]
I got this issue,too.Did you fix that?

**Comment by zesluo** [comment]
It has been fixed. Please try the latest version. Thanks for filing the issue
